import { EntityBase } from './entityBase';
import { Injectable} from '@angular/core';
import {
  core, MetadataStore, EntityType, AutoGeneratedKeyType, DataProperty, DataType,
  NavigationProperty, NavigationPropertyOptions
} from 'breeze-client';

@Injectable()
export class Sample extends EntityBase {

  id?: number;
  name?: string;
  detail?: string;
  type?: string;
  groundwaterLeeching?: string;

  jobSiteId?: number;

  constructor() {
    super();
  }

  public init(metadataStore:MetadataStore) {

    this.entityType = new EntityType({
      shortName: "Sample",
      namespace: "TDK",
      defaultResourceName: "Sample",
      autoGeneratedKeyType: AutoGeneratedKeyType.Identity,
      dataProperties: [
        new DataProperty({
          name: "id",
          dataType: DataType.Int32,
          isPartOfKey: true
        }),
        new DataProperty({
          name: "name",
          dataType: DataType.String
        }),
        new DataProperty({
          name: "detail",
          dataType: DataType.String
        }),
        new DataProperty({
          name: "type",
          dataType: DataType.String
        }),
        new DataProperty({
          name: "groundwaterLeeching",
          dataType: DataType.String
        }),
        new DataProperty({
          name: "jobSiteId",
          dataType: DataType.Int32
        }),
      ],
      navigationProperties: [
        new NavigationProperty(<NavigationPropertyOptions>{
          entityTypeName: "Sample:#TDK",
          associationName: "Sample_Job",
          name: "jobSite",
          isScalar: true,
          foreignKeyNames: ["jobSiteId"]
        })
      ]
    });

    metadataStore.addEntityType(this.entityType);
    metadataStore.registerEntityTypeCtor('Sample', Sample, Sample.initializer);
    this.entityType.createEntity();

  }
  /// [Initializer
  static initializer(entity:Sample) {
  }

}
